IF(WIN32)
    SET(CMAKE_DEBUG_POSTFIX d)
ENDIF(WIN32)


MACRO( ADD_SHARED_LIBRARY_INTERNAL TRGTNAME )
    ADD_LIBRARY( ${TRGTNAME} SHARED ${ARGN} )
    IF( WIN32 )
        SET_TARGET_PROPERTIES( ${TRGTNAME} PROPERTIES DEBUG_POSTFIX d )
    ENDIF( WIN32 )
    TARGET_LINK_LIBRARIES( ${TRGTNAME}
        ${OSGEPHEMERIS_LIBRARIES}
        ${OSGWORKS_LIBRARIES}
        ${OSG_LIBRARIES}
        ${OPENGL_LIBRARIES}
        ${PNG_LIBRARIES}
    )
    SET_TARGET_PROPERTIES( ${TRGTNAME} PROPERTIES PROJECT_LABEL "Lib ${TRGTNAME}" )
ENDMACRO( ADD_SHARED_LIBRARY_INTERNAL TRGTNAME )

MACRO( ADD_OSGPLUGIN TRGTNAME )
    ADD_LIBRARY( ${TRGTNAME} MODULE ${ARGN} )
    IF( WIN32 )
        SET_TARGET_PROPERTIES( ${TRGTNAME} PROPERTIES DEBUG_POSTFIX d )
    ENDIF( WIN32 )
    TARGET_LINK_LIBRARIES( ${TRGTNAME}
        backdropFX
        ${OSGEPHEMERIS_LIBRARIES}
        ${OSGWORKS_LIBRARIES}
        ${OSG_LIBRARIES}
        ${OPENGL_LIBRARIES}
        ${PNG_LIBRARIES}
    )
    SET_TARGET_PROPERTIES( ${TRGTNAME} PROPERTIES PREFIX "" )
    SET_TARGET_PROPERTIES( ${TRGTNAME} PROPERTIES PROJECT_LABEL "Plugin ${TRGTNAME}" )
ENDMACRO( ADD_OSGPLUGIN TRGTNAME )


MACRO( MAKE_EXECUTABLE EXENAME )
#    message( STATUS "making executable ${CATEGORY} ${EXENAME}" )
    ADD_EXECUTABLE_INTERNAL( ${EXENAME}
        ${ARGN}
    )
    TARGET_LINK_LIBRARIES( ${EXENAME}
        backdropFX
        ${OSGEPHEMERIS_LIBRARIES}
#        ${OSGBULLETPLUS_LIBRARIES}
#        ${OSGBULLET_LIBRARIES}
#        ${BULLET_LIBRARIES}
        ${OSGWORKS_LIBRARIES}
        ${OSG_LIBRARIES}
        ${OPENGL_LIBRARIES}
    )

    # Requires ${CATAGORY}
    IF( CATEGORY STREQUAL "App" )
        INSTALL(
            TARGETS ${EXENAME}
            RUNTIME DESTINATION bin COMPONENT libosgworks
        )
    ENDIF( CATEGORY STREQUAL "App" )
    SET_TARGET_PROPERTIES( ${EXENAME} PROPERTIES PROJECT_LABEL "${CATEGORY} ${EXENAME}" )
ENDMACRO( MAKE_EXECUTABLE EXENAME CATEGORY )

MACRO( MAKE_WX_EXECUTABLE EXENAME )
#    message( STATUS "making wx executable ${CATEGORY} ${EXENAME}" )
    ADD_DEFINITIONS( ${wxWidgets_DEFINITIONS} )
    ADD_EXECUTABLE_INTERNAL( ${EXENAME}
        WIN32
        ${ARGN}
    )
    TARGET_LINK_LIBRARIES( ${EXENAME}
        backdropFX
        ${OSGEPHEMERIS_LIBRARIES}
#        ${OSGBULLETPLUS_LIBRARIES}
#        ${OSGBULLET_LIBRARIES}
#        ${BULLET_LIBRARIES}
        ${OSGWXTREE_LIBRARIES}
        ${OSGWORKS_LIBRARIES}
        ${wxWidgets_LIBRARIES}
        ${OSG_LIBRARIES}
        ${OPENGL_LIBRARIES}
    )

    # Requires ${CATAGORY}
    IF( CATEGORY STREQUAL "App" )
        INSTALL(
            TARGETS ${EXENAME}
            RUNTIME DESTINATION bin COMPONENT libosgworks
        )
    ENDIF( CATEGORY STREQUAL "App" )
    SET_TARGET_PROPERTIES( ${EXENAME} PROPERTIES PROJECT_LABEL "${CATEGORY} ${EXENAME}" )
ENDMACRO( MAKE_WX_EXECUTABLE EXENAME CATEGORY )

MACRO( ADD_EXECUTABLE_INTERNAL TRGTNAME )
    ADD_EXECUTABLE( ${TRGTNAME} ${ARGN} )
    IF( WIN32 )
        SET_TARGET_PROPERTIES( ${TRGTNAME} PROPERTIES DEBUG_POSTFIX d )
    ENDIF(WIN32)
ENDMACRO( ADD_EXECUTABLE_INTERNAL TRGTNAME )

MACRO( LINK_INTERNAL TRGTNAME )
    FOREACH(LINKLIB ${ARGN})
        TARGET_LINK_LIBRARIES(${TRGTNAME} optimized "${LINKLIB}" debug "${LINKLIB}${CMAKE_DEBUG_POSTFIX}")
    ENDFOREACH(LINKLIB)
ENDMACRO( LINK_INTERNAL TRGTNAME )
